mimblewimble/grin-pm

notes/20181127-meeting-development.md

Fixes https://github.com/mimblewimble/grin-pm/issues/19

add Nov 27 dev notes

---

notes/20181204-meeting-governance.md

add gov-notes

---

README.md
notes/20181227-meeting-development.md

Fixes https://github.com/mimblewimble/grin-pm/issues/29

add Dec 27 dev meeting notes

---

README.md
decision_log.md
ecosystem/notes/YYYY-MM-DD-ecosystem-call.md
ecosystem/notes/YYYYMMDD-ecosystem-call.md
notes/20190122-meeting-development.md

Dev notes & tweaks

---

README.md
notes/20190205-meeting-development.md

add feb 5 developer meeting notes

---

README.md
decision_log.md
notes/20190212-meeting-governance.md

add feb 12 governance meeting notes

---

README.md
notes/20190226-meeting-governance.md

add Feb 26 governance notes

---

notes/20190226-meeting-governance.md

@lehnberg I think it's worth either pointing this out or remove the note altogether since there was no substantial reason provided for disagreeing.

Note on 20190226 governance meeting

---

decision_log.md

Add the decision to award funding to Antioch

update decision log

---

financials/income_log.csv

Add Hendi's grin-pool.org donation for February and update the donation entry of sparkpool.

income_log updates

---

README.md
notes/20190319-meeting-development.md

add Mar 19 dev notes

---

financials/income_log.csv

Someone please review/thumbs up this before I merge

add id 19 2Miners donation to income log

---

README.md
notes/20190402-meeting-development.md

add Apr 02 dev meeting notes

---

README.md
decision_log.md
notes/20190409-meeting-governance.md

add apr 09 governance notes

---

financials/income_log.csv

3490 grins and [58.48 eth](https://etherscan.io/tx/0xe0f9b1997cc416d1692d3da4a0ac136de98485e44c188280dfbc96276d64b983)

Sparkpool's 3rd donation

---

financials/income_log.csv

Adds March and April monthly donations by Poloniex to income logs. Would appreciate a review and an approval from someone in the community. ✌️

Add Poloniex donations

---

README.md
notes/20190423-meeting-governance.md

add apr 23 governance notes

---

financials/spending_log.csv

Brings the total to $30k as previously decided. Was missing about $4900 because of Grin's inflation that's way too high #rekt.

Completion of Igno Grin donation

---

README.md
notes/20190430-meeting-development.md

add Apr 30 dev meeting notes

---

financials/income_log.csv
financials/spending_log.csv

Seems highly unlikely we made and received grin donations in 2018. :)

fix: date corrections in logs

---

financials/income_log.csv

Transaction:  https://www.blockchain.com/btc/tx/491ee02543c25d729616de43685d837aa8461b453fd63da8eed88487db4176b7

Great anonymous donation of 50 BTC

---

financials/income_log.csv

for the https://github.com/mimblewimble/grin-pm/pull/132#issuecomment-490500566

fix the precision of btc

---

README.md
notes/20190514-meeeting-development.md

add May 14 dev notes

---

notes/20190514-meeeting-development.md

Unfortunately, I didn't make it to that meeting.

Remove kargakis from 20190514 dev meeting

---

financials/income_log.csv

value: 3953 GRIN
dst: https://donations.grin-tech.org
txid: "9e9d883a-32a5-44e3-8024-690df896c6e6"

record sparkpool's 4th donation

---

ecosystem/06042019-community-project-day.md

06042019-community-project-day meeting notes

06042019-community-project-day

---

financials/income_log.csv

https://www.blockchain.com/btc/tx/75755cf441de64ad14eb72a5ba002bd9b206fe0d2a4db226ebde48a56227bf3a

add gate.io donation to income log

---

README.md
decision_log.md
notes/20190618-meeting-governance.md

add Jun 18 governance meeting notes

---

README.md
decision_log.md
notes/20190625-meeting-development.md

add Jun 25 dev meeting notes

---

financials/income_log.csv

This PR adds donations to the income log from four individuals that wish to be included into Friends of Grin

update income log with friends of grin donations

---

README.md
decision_log.md
notes/20190702-meeting-governance.md

add Jul 02 governance meeting notes

---

README.md
notes/20190709-meeting-development.md

add Jul 09 development meeting notes

---

README.md
decision_log.md
notes/20190716-meeting-governance.md

add Jul 16 governance meeting notes

---

README.md
decision_log.md
notes/20190723-meeting-development.md

add Jul 23 dev notes

---

README.md
decision_log.md
notes/20190730-meeting-governance.md

add Jul 30 gov meeting notes

---

README.md
notes/20190813-meeting-governance.md

add Aug 13 governance meeting notes

---

README.md
notes/20190820-meeting-development.md

add Aug 20 dev meeting notes

---

README.md
decision_log.md
notes/20190827-meeting-governance.md

add Aug 27 governance meeting notes

---

README.md
notes/20190903-meeting-development.md

add sep 03 dev meeting notes

---

README.md
notes/20190910-meeting-governance.md

add sep 10 governance meeting notes

---

README.md
decision_log.md
notes/20190917-meeting-development.md

add Sep 17 dev notes

---

financials/income_log.csv

Add poloniex donation 7, fix historical ordering and donations 

---

README.md
notes/20191001-meeting-development.md

add Oct01 dev meeting notes

---

README.md
decision_log.md
notes/20191008-meeting-governance.md

add Oct 08 governance notes

---

financials/income_log.csv
financials/spending_log.csv

As per [governance meeting note](https://github.com/mimblewimble/grin-pm/blob/master/notes/20191008-meeting-governance.md#7-decision-approve-lehnberg-request-for-funding).
Would be good if somebody could review details and 👍 that it's accurate.
thanks!

update spending log for lehnberg donation

---

README.md
notes/20191029-meeting-development.md

add Oct 29 dev meeting notes

---

financials/addresses.md

This PR changes the project's donation addresses to a new multi-sig set up following Ignotus absence. Previous funds have been transferred over to the new addresses. As before, it is a `m-of-n` multi-sig controlled by core team members.

Update bitcoin donation addresses

---

README.md
notes/20191112-meeting-development.md

add Nov 12 dev meeting notes

---

README.md
decision_log.md
notes/20191119-meeting-governance.md

add Nov 19 governance meeting notes

---

README.md
notes/20191126-meeting-development.md

add Nov 26 dev meeting notes

---

README.md
decision_log.md
notes/20191203-meeting-governance.md

add Dec 03 gov meeting notes

---

README.md
notes/20191210-meeting-development.md

add Dec 10 dev notes

---

README.md
decision_log.md
notes/20191217-meeting-governance.md

add Dec 17 governance notes

---

financials/income_log.csv

adds TMGOX donation and a small donation from an unknown source

Update income log

---

financials/income_log.csv

This adds a series of smaller unknown donations from the bitcoin and grin wallets to the income log, in total equivalent to USD 85.27.

Add entries 178-184 to income log 

---

README.md
notes/20200107-meeting-development.md

add Jan 07 2020 dev notes

---

README.md
decision_log.md
notes/20200114-meeting-governance.md

Add Jan 14 governance notes

---

README.md
decision_log.md
notes/20200121-meeting-development.md

Add Jan 21 dev meeting notes

---

README.md
decision_log.md
notes/20200128-meeting-governance.md

Add Jan 28 2020 governance meeting notes

---

README.md
notes/20200204-meeting-development.md

add Feb 04 dev meeting notes

---

README.md
notes/20200211-meeting-governance.md

add Feb 11 gov meeting notes

---

README.md
notes/20200218-meeting-development.md

add Feb 18 dev notes

---

README.md
decision_log.md
notes/20200225-meeting-governance.md

Add Feb 25 governance notes

---

README.md
notes/20200317-meeting-development.md

add mar 17 dev meeting notes

---

README.md
decision_log.md
notes/20200324-meeting-governance.md

Add mar 24 governance meeting notes

---

README.md
notes/20200331-meeting-development.md

Add Mar 31 dev meeting notes

---

README.md
decision_log.md
notes/20200407-meeting-governance.md

Add april 7 governance meeting notes

---

README.md
notes/20200414-meeting-development.md

add Apr 14 dev meeting notes

---

README.md
notes/20200428-meeting-development.md

Add apr 28 development notes

---

README.md
notes/20200505-meeting-governance.md

Add may 05 governance meeting notes

---

README.md
decision_log.md
notes/20200512-meeting-development.md

add May 12 dev meeting notes

---

README.md
notes/20200519-meeting-governance.md

Add May 19 Governance Meeting Notes

---

README.md
notes/20200526-meeting-development.md

Add may 26 development meeting notes

---

README.md
notes/20200602-meeting-governance.md

add jun 02 governance meeting notes

---

README.md
notes/20200609-meeting-development.md

add jun 09 dev meeting notes

---

README.md
notes/20200616-meeting-governance.md

add jun 16 governance meeting notes

---

README.md
notes/20200623-meeting-development.md

Add jun 23 dev meeting notes

---

README.md
decision_log.md
notes/20200630-meeting-governance.md

Add jun 30 governance notes

---

README.md
notes/20200707-meeting-development.md

Add July 7 dev meeting notes

---

README.md
notes/20200714-meeting-governance.md

add July 14 governance meeting notes

---

README.md
notes/20200721-meeting-development.md

Add July 21 development meeting notes

---

README.md
decision_log.md
notes/20200728-meeting-governance.md

Add July 28 governance meeting notes

---

README.md
notes/20200804-meeting-development.md

Add Aug 04 dev meeting notes

---

README.md
notes/20200825-meeting-governance.md

Add Aug 25 governance meeting notes

---

README.md
decision_log.md
notes/20200908-meeting-governance.md

Add Sep 08 gov meeting notes

---

README.md
notes/20200915-meeting-development.md

Add Sep 15 dev meeting notes

---

README.md
decision_log.md
notes/20200922-meeting-governance.md

add Sep 22 gov meeting notes

---

README.md
notes/20200929-meeting-development.md

Add Sep 29 dev meeting notes

---

README.md
decision_log.md
notes/20201006-meeting-governance.md

add Oct 06 Governance notes

---

README.md
notes/20201013-meeting-development.md

Add Oct 13 dev notes

---

README.md
decision_log.md
notes/20201020-meeting-governance.md

Add Oct 20 gov notes

---

README.md
notes/20201027-meeting-development.md

Add Oct 27 dev notes

---

README.md
notes/20201103-meeting-governance.md

Add Nov 03 Governance notes

---

README.md
notes/20201110-meeting-development.md

Add Nov 10 dev notes

---

README.md
notes/20201117-meeting-governance.md

Add Nov 17 Governance meeting notes

---

README.md
notes/20201110-meeting-development.md
notes/20201124-meeting-development.md

Add Nov 24 dev notes

---

README.md
notes/20201117-meeting-governance.md
notes/20201201-meeting-governance.md

Add Dec 01 governance meeting notes

---

README.md
notes/20201208-meeting-development.md

Add Dec 08 dev meeting notes

---

README.md
decision_log.md
notes/20201215-meeting-governance.md

Add Dec 15 governance meeting notes

---

README.md
notes/20201222-meeting-development.md

Add Dec 22 dev meeting notes

---

financials/addresses.md

Replace grin https donation address with slatepack address

---

README.md
decision_log.md
notes/20210119-meeting-governance.md

Add Jan 19 Governance Notes

---

README.md
notes/20210202-meeting-governance.md

Add Feb 02 Governance Notes

---

README.md
decision_log.md
notes/20210216-meeting-governance.md

Add Feb 16 Governance notes

---

README.md
notes/20210223-meeting-development.md

Add Feb 23 Dev meeting notes

---

README.md
decision_log.md
notes/20210302-meeting-governance.md

Add Mar 02 governance notes

---

financials/reports/funding_transparency_2020Q4.md

`ref_balance` checks out:
```
{
"tx_hash": "5c75c669f4808b88a151b8e867a5aede075a0611f294c27365dd5b1fa9856913",
"block_height": 662519,
"tx_input_n": 0,
"tx_output_n": -1,
"value": 1000000000,
"ref_balance": 9687264400,
"confirmations": 12058,
"confirmed": "2020-12-22T17:18:29Z",
"double_spend": false
}
```
https://api.blockcypher.com/v1/btc/main/addrs/bc1qecw954uappnwhle6tmafqskn6vxmpr6lmmuwfwldphfxplcshgnssy9kmx

Add 2020 Q4 financial transparency report

---

README.md
notes/20210323-meeting-development.md

Add Mar 23 meeting notes

---

financials/addresses.md

Outdated addresses, removing in favour of single BTC segwit address. Also correct the current donation address (!)

Remove Bitcoin legacy and Grin addresses
